### ISSUE TITLE
Origin

### ISSUE THREAD

**Issue by oroce** [purposeindustries/window-or-global#1]
We should state we borrowed this from underscore: https://github.com/megawac/underscore/commit/365311c9a440438531ca1c6bfd49e3c7c5f46079

**Comment by ruffle1986** [comment]
as a code comment or in the readme?

**Comment by oroce** [comment]
I think we should just mention in the readme

**Comment by ruffle1986** [comment]
could you please open a pull request?

**Comment by oroce** [comment]
Sure

**Comment by oroce** [comment]
see #2
