### ISSUE TITLE
addEventListener not a function!

### ISSUE THREAD

**Issue by kasra-localid** [purposeindustries/window-or-global#4]
is this module not maintained anymore? when I want to use the `addEventListener` method, it throws an error that it's not a function!

**Comment by oroce** [comment]
This module returns either the `window` if you are in a browser or the `global` object in node.

Since `global` in node has no method called `addEventListener`, it will throw error.
```
$> node -pe 'global.addEventListener'                                                                                                                                   
undefined
```

We won't simulate the window in node, nor the global in the browser.
